### ISSUE TITLE
block direct access to CMS

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#17]
We now provide users with links from the website to our CMS and LMS. i.e. to go to https://contentmanagement.srisathyasaividyavahini.org/ and https://learning.srisathyasaividyavahini.org/. Can we block direct access to the CMS and LMS if users use the above URLs– which means that all our users will have to come to https:// [srisathyasaividyavahini.org](http://srisathyasaividyavahini.org/) and then go to CMS or LMS.  This way our own volunteers will visit the site more often and see the updates / changes etc.

P. Hariharan

IT Coordinator

Sri Sathya Sai Vidya Vahini (SSSVV)

**Comment by hn-88** [comment]
This is technically difficult / impossible to implement without some functionality breaking. What can be implemented :

(a) have some sort of landing page link in cms and lms
(b) have some sort of manually created notification to users in lms and cms - both of these have provision for that, I believe - to show users a link to some newly modified page which might be of interest to them.
