### ISSUE TITLE
mandala magnifier

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#20]
The Mandala new file will also replace the existing one in the “About Us” page. Can the
Mandala have a magnifier feature on this page itself for the visitors to magnify and go
through it in detail? It is an intricate piece of art that captures the 360 degrees vision of
SSSVV. Historians will learn about Bhagawan&#39;s educational renaissance by studying it to
understand how it played out. Every tiny detail is a Bhagawatham in itself.

**Comment by hn-88** [comment]
https://htmldom.dev/drag-to-scroll/

**Comment by hn-88** [comment]
https://www.w3schools.com/howto/howto_css_fixed_menu.asp

**Comment by hn-88** [comment]
scrollto does not work for some reason. transform works.
https://stackoverflow.com/questions/29633243/how-to-center-a-scrollable-image-that-is-larger-than-the-screen
adding css property
transform: translate(-50%, -50%);

**Comment by hn-88** [comment]
transform causes the left and top of the image to become un-reachable by scroll. Have currently put the transform at -1%.

**Comment by hn-88** [comment]
https://stackoverflow.com/questions/1564298/how-to-show-loading-image-when-a-big-image-is-being-loaded

**Comment by hn-88** [comment]
Closed with https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/1e1a630e3671fbd7115f1e0b02771efe3dbdde85
