### ISSUE TITLE
stats change

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#22]
In the Activities section where we are giving the statistics, please retain the 8,92,000,
2,700+, 32,000+, and 4,26,000+ figures along with the corresponding description. (You need
to just put the commas as per the Indian numbering system as I have done above). Please
remove 51, 7500+, 1.75+ million minutes and the corresponding descriptions. In short,
instead of having 7 stats, we will have only 4. Further, right now the 8,92,000 and its
corresponding description is with a larger font. Please make all 4 Stats with the same font
size.

**Comment by hn-88** [comment]
Need to undo the commit at
https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/fba1064121c815864788d7de405ae8c4dc3452f6
