### ISSUE TITLE
mission English page change 3

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#27]
In the Mission English page following change to be effected:
2. Sain In–The English App Logo to be shifted from the top (in change 1) to appear next to this title. This
will be numbered as offering 2.
Existing text, video to come under this.

**Comment by hn-88** [comment]
need to change create a new small sainin logo, since the one on the top is part of banner and has a large blue background.
