### ISSUE TITLE
check content creation page LHS unknown

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#3]
not rendering on webflow.io also for me, redo html?

**Comment by hn-88** [comment]
image link had spaces, corrected. https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/34832d883b5c1df8eb79fd5eda06f8936764b1af Also, tried different strategy without srcset, seemed to work.
