### ISSUE TITLE
new subpage last quarter

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#31]
We would like to start a new sub page called “Last Quarter achievements”. This would come
on the main banner after Testimonials. When one clicks on the “Last Quarter achievements”
a new sub page to open (We will keep updating this every quarter).

**Comment by hn-88** [comment]
This will affect #18 as well, so must try out suitable @media screen and max-width pixel values in css.

**Comment by SriSathyaSaiVidyaVahini** [comment]
For the Last Quarter achievements – we change the heading to “Quarter One – Milestones”. The revised write up is attached in the file “Quarter One”. Please replace accordingly. For the Leadership Program in this write up, there is a graphic also which will go alongside the write up which is attached separately.

**Comment by hn-88** [comment]
Added links to all pages as "Quarterly Milestones".
