### ISSUE TITLE
Add Activity SOPAAN

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#33]
Under SSSVV activities we have 5 activities – We now add a 6th one called SOPAAN. This will be another sub page just as we have for the other 5 activities. The write up is given in the link below

**Comment by hn-88** [comment]
please suggest suitable text for SOPAAN on home page.

(I would suggest something like
SOPAAN stands for S??? O??? P?? etc which is a bilingual, foundational learning program for children aimed at developing their passion and confidence for reading and lifelong learning. SOPAAN is currently active in <geographical locations>. To know more about SSSVV's SOPAAN, click here. )

**Comment by hn-88** [comment]
TODO - add sopaan to all footers as well as headers

**Comment by hn-88** [comment]
reduce padding in home page so that SOPAAN button also comes in the first line instead of wrapping.

**Comment by hn-88** [comment]
finished this with sopaan button on home page.

**Comment by hn-88** [comment]
add links which are mentioned in the Word Doc
