### ISSUE TITLE
Content Dissemination text/image relative size edit

### ISSUE THREAD

**Issue by SriSathyaSaiVidyaVahini** [SriSathyaSaiVidyaVahini/SSSVV-landing#36]
In the Content Dissemination and Training page – you have added the “Activities of the SSSVV Training Team”. Here the text is long whereas the accompanying images alongside are small. So request if you could increase the width of the text column so that the gap between the text and the images and also above / below the images is reduced. See attached screenshot with red arrow for the space to be reduced.

**Comment by hn-88** [comment]
Done. Also made the image slightly bigger, and added links so that clicking on the images opens the images in a new tab.
