### ISSUE TITLE
made in webflow js

### ISSUE THREAD

**Issue by hn-88** [SriSathyaSaiVidyaVahini/SSSVV-landing#4]
Displayed for some clients? To be removed.

**Comment by hn-88** [comment]
commented out entire webflow js file with https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/acca8a99589e2f139cb6288fae6724365d3447c7

Need to see if this causes any other issues.

**Comment by hn-88** [comment]
The webflow js was needed for carousel views etc. So, changed attrib to SSSVV team instead of webflow. Maybe that will work? https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/89c4d5bac0f28ec3dd4ce4c9fb62240fe0d945ec

**Comment by vlsubramanian** [comment]
Sairam Bro.,

The 'Web flow' is no longer appearing. Thanks.

However, now I see in the same bottom RHS, 2 SSSVV logos appearing for
Multimedia page. This appears only for this page and not for another
sections. Also, could you please correct the SSSCHV link in the bottom of
the page? It is given as http://www.ssschv.srisathyasai.org/, whereas it
should be https://ssschv.srisathyasai.org/ This was reported multiple times
but was not corrected by the developer. Thanks.

[image: image.png]
Loving Sairam

V L Subramanian
Planning & Strategy Lead
Sri Sathya Sai Vidya Vahini
Mob: +91 810 5658 625

**Comment by SriSathyaSaiVidyaVahini** [comment]
ssschv link corrected in all pages with https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/80c2486bc2b832a1e5287e0bd8f898d48567c090

**Comment by SriSathyaSaiVidyaVahini** [comment]
https://github.com/SriSathyaSaiVidyaVahini/SSSVV-landing/commit/fbe4d1a65dc8b25060c2c925c85325cd5b1ca4de should stop the popup on bottom right with SSSVV logo.

**Comment by vlsubramanian** [comment]
Thanks a lot.

Loving Sairam

V L Subramanian
Planning & Strategy Lead
Sri Sathya Sai Vidya Vahini
Mob: +91 810 5658 625
